apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tajogvi35-nodejs 
  janus-idp.io/tekton: tajogvi35-nodejs
  backstage.io/kubernetes-id: tajogvi35-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tajogvi35-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  