apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tajogvi35-nodejs
  janus-idp.io/tekton: tajogvi35-nodejs
  backstage.io/kubernetes-id: tajogvi35-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tajogvi35-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
